# site properties and page defaults
title: The Information Engineering Lab
short_title: ielab.io
subtitle: IELab @ UQ | The University of Queensland
description: The ielab is a collaborative group of researchers working in the area of information engineering. Much of this research is specifically on the areas of information retrieval, i.e. search engine technology and information seeking, data science, and health informatics.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  # email: contact@your-lab.com
  # orcid: 
  # google-scholar: 
  github: ielab
  twitter: ielabgroup
  youtube: ielab3142

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_grants
  - scope:
      type: "grants"
    values:
      layout: grant
  # markdown files in /_tutorials
  - scope:
      type: "tutorials"
    values:
      layout: tutorial

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each grant
  grants:
    output: true
  # generate page for each tutorial
  tutorials:
    output: true
  # generate page for each project
  projects:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
