name: first-time-setup
run-name: first time setup of repo

on:
  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write

jobs:
  first-time-setup:
    runs-on: ubuntu-latest

    steps:
      # for debugging
      - uses: crazy-max/ghaction-dump-context@v2

      - name: Create Pages branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "gh-pages"

      - name: Checkout Pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      # for debugging
      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      # clean slate, as if starting from orphan branch
      - name: Clear Pages branch
        run: rm -rf * .github .docker .gitignore

      # prevent GitHub from running Jekyll a second time after build
      - name: Make .nojekyll file
        run: touch .nojekyll

      - name: Make placeholder homepage
        run: printf "Placeholder homepage" > index.html

      - name: Commit changes to Pages branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: gh-pages
          commit_message: "Clear branch"

      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Remove files user doesn't need
        run: |
          rm -rf \
            CHANGELOG.md \
            testbed.md \
            .github/ISSUE_TEMPLATE \
            .github/DISCUSSION_TEMPLATE \
            .github/workflows/versioning.yaml \
            .github/pull_request_template.md \

      - name: Rename files
        run: |
          mv -f .github/user_pull_request_template.md .github/pull_request_template.md

      - name: Set vars for personalization
        run: |
          user="${{ github.repository_owner }}"
          description="The ielab is a collaborative group of researchers working in the area of information engineering. Much of this research is specifically on the areas of information retrieval, i.e. search engine technology and information seeking, data science, and health informatics."
          printf "USER=${user}" >> $GITHUB_ENV
          printf "DESCRIPTION=${description}" >> $GITHUB_ENV

      - name: Personalize Jekyll config for user
        uses: actions/github-script@v7
        with:
          script: |
            const { readFileSync, writeFileSync } = require("fs");
            const file = "_config.yaml";
            const contents = readFileSync(file)
              .toString()
              .replace(/(^title: ).*$/m, "$1The Information Engineering Lab")
              .replace(/(^subtitle: ).*$/m, "$1IELab @ UQ | The University of Queensland")
              .replace(/(^description: ).*$/m, "$1${{ env.DESCRIPTION }}")
              .replace(/(^  email: ).*$/m, "$1ielab@uq.edu.au")
              .replace(/(^  github: ).*$/m, "$1ielab")
              .replace(/(^  twitter: ).*$/m, "$1ielabgroup")
              .replace(/(^  youtube: ).*$/m, "$1ielab3142");
            writeFileSync(file, contents);

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Setup repo"
