name: on-pages
run-name: on pages deploy

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed
    branches:
      - gh-pages

  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-site:
    uses: ./.github/workflows/build-site.yaml
